"""Pydantic schemas for LLM-generated test scenarios."""

from pydantic import BaseModel, Field


class GeneratedScenario(BaseModel):
    """A test scenario generated by the LLM.

    This schema is used for structured output from the LLM when generating
    test scenarios based on agent configuration and personas.
    """

    name: str = Field(..., description="Short, descriptive name for the scenario")
    goal: str = Field(..., description="What the simulated user is trying to accomplish")
    intent: str = Field(..., description="The underlying user intent (e.g., check_order_status)")
    persona_traits: list[str] = Field(
        default_factory=list,
        description="Personality traits that would be ideal for this scenario",
    )
    max_turns: int = Field(
        default=10,
        ge=1,
        le=50,
        description="Suggested maximum conversation turns",
    )


class GeneratedScenariosResponse(BaseModel):
    """Response from LLM containing generated scenarios.

    This schema is used for structured output from the LLM containing
    a list of generated test scenarios.
    """

    scenarios: list[GeneratedScenario] = Field(..., description="List of generated test scenarios")
