"""Master vocabulary of valid persona traits.

This module defines the canonical list of traits that can be assigned to personas
and generated by the LLM. Both personas and LLM scenario generation must use
traits from this vocabulary to ensure matching works correctly.
"""

TRAIT_VOCABULARY: dict[str, list[str]] = {
    "emotional_state": [
        "angry",
        "frustrated",
        "calm",
        "anxious",
        "cheerful",
        "neutral",
        "irritated",
        "nervous",
    ],
    "communication_style": [
        "verbose",
        "terse",
        "indirect",
        "assertive",
        "polite",
        "blunt",
        "formal",
        "casual",
    ],
    "patience_level": [
        "impatient",
        "patient",
        "rushed",
        "relaxed",
    ],
    "cooperation": [
        "cooperative",
        "uncooperative",
        "demanding",
        "agreeable",
        "difficult",
        "flexible",
    ],
    "expertise": [
        "confused",
        "knowledgeable",
        "first-time-user",
        "tech-savvy",
        "inexperienced",
        "expert",
    ],
}

ALL_TRAITS: list[str] = [trait for traits in TRAIT_VOCABULARY.values() for trait in traits]
