/**
 * Mock data for voiceobs API endpoints.
 * This data is used by API stubs when the backend is not available.
 */

import type {
  TestSuite,
  TestScenario,
  TestExecution,
  Pipeline,
  Persona,
  Report,
  ScheduledReport,
  ReportHistoryItem,
  AgentListItem,
} from "./types";

// Mock Test Suites
export const mockTestSuites: TestSuite[] = [
  {
    id: "suite-001",
    name: "Regression Suite",
    description: "Daily regression tests for core functionality",
    status: "completed",
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "suite-002",
    name: "Smoke Tests",
    description: "Quick smoke tests for critical paths",
    status: "running",
    created_at: "2024-01-15T09:00:00Z",
  },
  {
    id: "suite-003",
    name: "Integration Tests",
    description: "End-to-end integration test scenarios",
    status: "pending",
    created_at: "2024-01-14T15:30:00Z",
  },
  {
    id: "suite-004",
    name: "Performance Tests",
    description: "Latency and throughput performance tests",
    status: "completed",
    created_at: "2024-01-14T12:00:00Z",
  },
];

// Mock Test Scenarios
export const mockTestScenarios: TestScenario[] = [
  {
    id: "scenario-001",
    suite_id: "suite-001",
    name: "Order Status Check",
    goal: "User checks the status of their recent order",
    persona_json: {
      role: "customer",
      tone: "polite",
      aggression: 0.2,
      patience: 0.8,
      verbosity: 0.5,
    },
    max_turns: 10,
    timeout: 300,
  },
  {
    id: "scenario-002",
    suite_id: "suite-001",
    name: "Payment Processing",
    goal: "User processes a payment for an order",
    persona_json: {
      role: "customer",
      tone: "professional",
      aggression: 0.1,
      patience: 0.9,
      verbosity: 0.4,
    },
    max_turns: 15,
    timeout: 600,
  },
  {
    id: "scenario-003",
    suite_id: "suite-002",
    name: "Quick Greeting",
    goal: "User greets the assistant and asks a simple question",
    persona_json: {
      role: "user",
      tone: "friendly",
      aggression: 0.0,
      patience: 0.7,
      verbosity: 0.3,
    },
    max_turns: 5,
    timeout: 120,
  },
  {
    id: "scenario-004",
    suite_id: "suite-002",
    name: "Error Handling",
    goal: "User encounters an error and needs help resolving it",
    persona_json: {
      role: "customer",
      tone: "frustrated",
      aggression: 0.6,
      patience: 0.3,
      verbosity: 0.7,
    },
    max_turns: 12,
    timeout: 400,
  },
  {
    id: "scenario-005",
    suite_id: "suite-003",
    name: "Multi-Turn Conversation",
    goal: "User engages in a complex multi-turn conversation",
    persona_json: {
      role: "user",
      tone: "curious",
      aggression: 0.3,
      patience: 0.6,
      verbosity: 0.8,
    },
    max_turns: 20,
    timeout: 900,
  },
  {
    id: "scenario-006",
    suite_id: "suite-004",
    name: "High Load Test",
    goal: "Simulate high concurrent load scenario",
    persona_json: {
      role: "user",
      tone: "neutral",
      aggression: 0.2,
      patience: 0.5,
      verbosity: 0.4,
    },
    max_turns: 8,
    timeout: 200,
  },
];

// Mock Test Executions
export const mockTestExecutions: TestExecution[] = [
  {
    id: "execution-001",
    scenario_id: "scenario-001",
    conversation_id: "conv-001",
    status: "completed",
    started_at: "2024-01-15T10:00:00Z",
    completed_at: "2024-01-15T10:05:30Z",
    result_json: {
      passed: true,
      score: 0.95,
      duration_ms: 330000,
      turns_completed: 8,
      latency_p50_ms: 850,
      latency_p95_ms: 1200,
    },
  },
  {
    id: "execution-002",
    scenario_id: "scenario-002",
    conversation_id: "conv-002",
    status: "completed",
    started_at: "2024-01-15T10:06:00Z",
    completed_at: "2024-01-15T10:12:15Z",
    result_json: {
      passed: true,
      score: 0.88,
      duration_ms: 375000,
      turns_completed: 12,
      latency_p50_ms: 920,
      latency_p95_ms: 1350,
    },
  },
  {
    id: "execution-003",
    scenario_id: "scenario-003",
    conversation_id: "conv-003",
    status: "running",
    started_at: "2024-01-15T10:15:00Z",
    completed_at: null,
    result_json: {},
  },
  {
    id: "execution-004",
    scenario_id: "scenario-004",
    conversation_id: "conv-004",
    status: "failed",
    started_at: "2024-01-15T09:30:00Z",
    completed_at: "2024-01-15T09:35:20Z",
    result_json: {
      passed: false,
      score: 0.45,
      duration_ms: 320000,
      turns_completed: 6,
      error: "Timeout exceeded",
      latency_p50_ms: 2100,
      latency_p95_ms: 3500,
    },
  },
  {
    id: "execution-005",
    scenario_id: "scenario-001",
    conversation_id: "conv-005",
    status: "queued",
    started_at: null,
    completed_at: null,
    result_json: {},
  },
  {
    id: "execution-006",
    scenario_id: "scenario-005",
    conversation_id: "conv-006",
    status: "completed",
    started_at: "2024-01-14T14:00:00Z",
    completed_at: "2024-01-14T14:18:45Z",
    result_json: {
      passed: true,
      score: 0.92,
      duration_ms: 1125000,
      turns_completed: 18,
      latency_p50_ms: 780,
      latency_p95_ms: 1100,
    },
  },
];

// Mock Pipelines
export const mockPipelines: Pipeline[] = [
  {
    id: "pipeline-001",
    name: "Production Pipeline",
    description: "Main production voice AI pipeline",
    config: {
      asr_provider: "deepgram",
      llm_provider: "openai",
      tts_provider: "elevenlabs",
      model: "gpt-4",
      temperature: 0.7,
    },
    status: "active",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-01-15T09:00:00Z",
  },
  {
    id: "pipeline-002",
    name: "Staging Pipeline",
    description: "Staging environment pipeline for testing",
    config: {
      asr_provider: "deepgram",
      llm_provider: "anthropic",
      tts_provider: "elevenlabs",
      model: "claude-3-opus",
      temperature: 0.5,
    },
    status: "active",
    created_at: "2024-01-12T10:00:00Z",
    updated_at: "2024-01-14T15:00:00Z",
  },
  {
    id: "pipeline-003",
    name: "Development Pipeline",
    description: "Development pipeline with experimental features",
    config: {
      asr_provider: "whisper",
      llm_provider: "openai",
      tts_provider: "openai",
      model: "gpt-3.5-turbo",
      temperature: 0.8,
    },
    status: "inactive",
    created_at: "2024-01-08T12:00:00Z",
    updated_at: "2024-01-13T11:00:00Z",
  },
  {
    id: "pipeline-004",
    name: "Legacy Pipeline",
    description: "Archived legacy pipeline configuration",
    config: {
      asr_provider: "google",
      llm_provider: "openai",
      tts_provider: "google",
      model: "gpt-3",
      temperature: 0.6,
    },
    status: "archived",
    created_at: "2023-12-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// Mock Personas (including predefined ones)
export const mockPersonas: Persona[] = [
  {
    id: "persona-001",
    name: "Polite Customer",
    description: "A polite and patient customer persona",
    aggression: 0.2,
    patience: 0.8,
    verbosity: 0.5,
    traits: ["polite", "patient", "clear"],
    accent: "american",
    gender: "neutral",
    background_noise: false,
    temperature: 0.7,
    enabled: true,
    is_predefined: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: null,
  },
  {
    id: "persona-002",
    name: "Frustrated User",
    description: "An impatient and frustrated user persona",
    aggression: 0.7,
    patience: 0.2,
    verbosity: 0.6,
    traits: ["frustrated", "impatient", "direct"],
    accent: "american",
    gender: "male",
    background_noise: true,
    temperature: 0.8,
    enabled: true,
    is_predefined: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: null,
  },
  {
    id: "persona-003",
    name: "Professional Business",
    description: "A professional business user persona",
    aggression: 0.1,
    patience: 0.9,
    verbosity: 0.4,
    traits: ["professional", "efficient", "formal"],
    accent: "british",
    gender: "neutral",
    background_noise: false,
    temperature: 0.6,
    enabled: true,
    is_predefined: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: null,
  },
  {
    id: "persona-004",
    name: "Chatty User",
    description: "A verbose and friendly user persona",
    aggression: 0.0,
    patience: 0.7,
    verbosity: 0.9,
    traits: ["friendly", "verbose", "enthusiastic"],
    accent: "australian",
    gender: "female",
    background_noise: false,
    temperature: 0.9,
    enabled: true,
    is_predefined: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: null,
  },
  {
    id: "persona-005",
    name: "Quick Decision Maker",
    description: "A concise and decisive user persona",
    aggression: 0.3,
    patience: 0.5,
    verbosity: 0.2,
    traits: ["decisive", "concise", "focused"],
    accent: "canadian",
    gender: "male",
    background_noise: false,
    temperature: 0.5,
    enabled: true,
    is_predefined: false,
    created_at: "2024-01-12T14:30:00Z",
    updated_at: "2024-01-13T10:00:00Z",
  },
  {
    id: "persona-006",
    name: "Technical Expert",
    description: "A technical expert with high verbosity",
    aggression: 0.2,
    patience: 0.6,
    verbosity: 0.8,
    traits: ["technical", "detailed", "precise"],
    accent: "indian",
    gender: "neutral",
    background_noise: true,
    temperature: 0.7,
    enabled: false,
    is_predefined: false,
    created_at: "2024-01-14T09:15:00Z",
    updated_at: null,
  },
];

// Mock Reports
export const mockReports: Report[] = [
  {
    id: "report-001",
    name: "Weekly Summary Report",
    type: "summary",
    format: "pdf",
    status: "completed",
    config: {
      date_range: "2024-01-08 to 2024-01-15",
      include_charts: true,
    },
    generated_at: "2024-01-15T10:00:00Z",
    download_url: "/api/reports/report-001/download",
    created_at: "2024-01-15T09:55:00Z",
  },
  {
    id: "report-002",
    name: "Detailed Test Analysis",
    type: "detailed",
    format: "json",
    status: "completed",
    config: {
      suite_id: "suite-001",
      include_executions: true,
      include_metrics: true,
    },
    generated_at: "2024-01-14T16:30:00Z",
    download_url: "/api/reports/report-002/download",
    created_at: "2024-01-14T16:25:00Z",
  },
  {
    id: "report-003",
    name: "Performance Comparison",
    type: "comparison",
    format: "html",
    status: "generating",
    config: {
      baseline_suite: "suite-001",
      comparison_suite: "suite-004",
    },
    generated_at: null,
    download_url: null,
    created_at: "2024-01-15T10:30:00Z",
  },
];

// Mock Scheduled Reports
export const mockScheduledReports: ScheduledReport[] = [
  {
    id: "schedule-001",
    name: "Daily Summary",
    report_type: "summary",
    format: "pdf",
    schedule: "0 9 * * *", // Daily at 9 AM
    config: {
      include_charts: true,
    },
    is_active: true,
    last_run: "2024-01-15T09:00:00Z",
    next_run: "2024-01-16T09:00:00Z",
    created_at: "2024-01-10T08:00:00Z",
  },
  {
    id: "schedule-002",
    name: "Weekly Detailed Report",
    report_type: "detailed",
    format: "json",
    schedule: "0 10 * * 1", // Every Monday at 10 AM
    config: {
      suite_id: "suite-001",
    },
    is_active: true,
    last_run: "2024-01-15T10:00:00Z",
    next_run: "2024-01-22T10:00:00Z",
    created_at: "2024-01-08T12:00:00Z",
  },
  {
    id: "schedule-003",
    name: "Monthly Trend Analysis",
    report_type: "trend",
    format: "pdf",
    schedule: "0 8 1 * *", // First day of month at 8 AM
    config: {
      lookback_days: 30,
    },
    is_active: false,
    last_run: "2024-01-01T08:00:00Z",
    next_run: "2024-02-01T08:00:00Z",
    created_at: "2023-12-15T10:00:00Z",
  },
];

// Mock Report History
export const mockReportHistory: ReportHistoryItem[] = [
  {
    id: "history-001",
    report_id: "report-001",
    name: "Weekly Summary Report",
    status: "completed",
    generated_at: "2024-01-15T10:00:00Z",
    download_url: "/api/reports/report-001/download",
  },
  {
    id: "history-002",
    report_id: "report-002",
    name: "Detailed Test Analysis",
    status: "completed",
    generated_at: "2024-01-14T16:30:00Z",
    download_url: "/api/reports/report-002/download",
  },
  {
    id: "history-003",
    report_id: "report-003",
    name: "Performance Comparison",
    status: "generating",
    generated_at: null,
    download_url: null,
  },
  {
    id: "history-004",
    report_id: "report-004",
    name: "Weekly Summary Report",
    status: "completed",
    generated_at: "2024-01-08T09:00:00Z",
    download_url: "/api/reports/report-004/download",
  },
  {
    id: "history-005",
    report_id: "report-005",
    name: "Failed Report Generation",
    status: "failed",
    generated_at: "2024-01-07T10:00:00Z",
    download_url: null,
  },
];

// Mock Agents
export const mockAgents: AgentListItem[] = [
  {
    id: "agent-001",
    name: "Flight Booking Agent",
    description: "Handles flight reservations, bookings, and schedule inquiries",
    phone_number: "+1 (555) 123-4567",
    status: "active",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-01-15T09:00:00Z",
    calls: 1892,
    success_rate: 95.2,
    latency: 212,
  },
  {
    id: "agent-002",
    name: "Customer Support Agent",
    description: "Provides customer support and resolves issues",
    phone_number: "+1 (555) 234-5678",
    status: "active",
    created_at: "2024-01-11T10:00:00Z",
    updated_at: "2024-01-14T15:00:00Z",
    calls: 634,
    success_rate: 97.8,
    latency: 189,
  },
  {
    id: "agent-003",
    name: "Cancellation Agent",
    description: "Handles booking cancellations and refunds",
    phone_number: "+1 (555) 345-6789",
    status: "active",
    created_at: "2024-01-12T12:00:00Z",
    updated_at: "2024-01-13T11:00:00Z",
    calls: 321,
    success_rate: 89.4,
    latency: 267,
  },
  {
    id: "agent-004",
    name: "Healthcare Appointment Scheduler",
    description: "Schedules and manages healthcare appointments",
    phone_number: "+1 (555) 456-7890",
    status: "active",
    created_at: "2024-01-08T09:00:00Z",
    updated_at: "2024-01-15T08:30:00Z",
    calls: 1245,
    success_rate: 96.5,
    latency: 198,
  },
  {
    id: "agent-005",
    name: "Voice Banking Assistant",
    description: "Assists with banking transactions and account inquiries",
    phone_number: "+1 (555) 567-8901",
    status: "inactive",
    created_at: "2024-01-09T11:00:00Z",
    updated_at: "2024-01-14T14:00:00Z",
    calls: 892,
    success_rate: 92.3,
    latency: 234,
  },
  {
    id: "agent-006",
    name: "Real-time Translation",
    description: "Provides real-time translation services",
    phone_number: "+1 (555) 678-9012",
    status: "inactive",
    created_at: "2024-01-07T13:00:00Z",
    updated_at: "2024-01-12T10:00:00Z",
    calls: 456,
    success_rate: 88.7,
    latency: 289,
  },
  {
    id: "agent-007",
    name: "Legacy Support Agent",
    description: "Legacy agent for backward compatibility",
    phone_number: "+1 (555) 789-0123",
    status: "archived",
    created_at: "2023-12-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    calls: 2156,
    success_rate: 85.2,
    latency: 312,
  },
];
